FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Get source code and checkout master branch
COPY lyrion-fastapi.tar lyrion-fastapi.tar
ADD lyrion-fastapi.tar /app


# Create environment
RUN pip3 install -r requirements.txt

# Expose Port
EXPOSE 8000

# run shell script
RUN chmod +x startup.sh
ENTRYPOINT ["bash", "startup.sh"]